// <auto-generated />
using System;
using MVCAuctionPortal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCAuctionPortal.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20230424211336_addtot")]
    partial class addtot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuctionPortal.Models.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressID"));

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressID");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            AddressID = 1,
                            HouseNumber = "10",
                            LocalNumber = "1",
                            Street = "Main Street",
                            ZipCode = "12345"
                        },
                        new
                        {
                            AddressID = 2,
                            HouseNumber = "5",
                            LocalNumber = "3",
                            Street = "Park Avenue",
                            ZipCode = "54321"
                        },
                        new
                        {
                            AddressID = 3,
                            HouseNumber = "27",
                            LocalNumber = "2",
                            Street = "Broadway",
                            ZipCode = "67890"
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.Auction", b =>
                {
                    b.Property<int>("AuctionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionID"));

                    b.Property<bool>("BuyItNow")
                        .HasColumnType("bit");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("Pieces")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PurchaseCounter")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("WarrantyID")
                        .HasColumnType("int");

                    b.HasKey("AuctionID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ItemID");

                    b.HasIndex("SubCategoryID");

                    b.HasIndex("UserID");

                    b.HasIndex("WarrantyID");

                    b.ToTable("Auction");

                    b.HasData(
                        new
                        {
                            AuctionID = 1,
                            BuyItNow = false,
                            DateOfIssue = new DateTime(2023, 4, 24, 23, 13, 36, 452, DateTimeKind.Local).AddTicks(3045),
                            EndDate = new DateTime(2023, 5, 1, 23, 13, 36, 452, DateTimeKind.Local).AddTicks(3079),
                            ImageURL = "https://m.media-amazon.com/images/I/71dpTXFz+dL._AC_UF1000,1000_QL80_.jpg",
                            ItemID = 1,
                            Pieces = 5,
                            Price = 100m,
                            PurchaseCounter = 0,
                            SubCategoryID = 1,
                            Title = "Iphone",
                            UserID = 2,
                            WarrantyID = 1
                        },
                        new
                        {
                            AuctionID = 2,
                            BuyItNow = true,
                            DateOfIssue = new DateTime(2023, 4, 24, 23, 13, 36, 452, DateTimeKind.Local).AddTicks(3088),
                            EndDate = new DateTime(2023, 5, 8, 23, 13, 36, 452, DateTimeKind.Local).AddTicks(3090),
                            ImageURL = "https://grube.pl/wp-content/uploads/2017/07/product-135.jpg",
                            ItemID = 2,
                            Pieces = 3,
                            Price = 200m,
                            PurchaseCounter = 0,
                            SubCategoryID = 2,
                            Title = "Shovel",
                            UserID = 2,
                            WarrantyID = 2
                        },
                        new
                        {
                            AuctionID = 3,
                            BuyItNow = false,
                            DateOfIssue = new DateTime(2023, 4, 24, 23, 13, 36, 452, DateTimeKind.Local).AddTicks(3093),
                            EndDate = new DateTime(2023, 5, 15, 23, 13, 36, 452, DateTimeKind.Local).AddTicks(3096),
                            ImageURL = "https://a.allegroimg.com/original/1e76f9/ba5267f249a8bb358f5d3cf50ec6",
                            ItemID = 3,
                            Pieces = 1,
                            Price = 300m,
                            PurchaseCounter = 0,
                            SubCategoryID = 3,
                            Title = "Boots",
                            UserID = 2,
                            WarrantyID = 3
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<int>("CompanyAddressID")
                        .HasColumnType("int");

                    b.Property<string>("CountryEstablishment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("DateOfEstablishment")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Regon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CompanyID");

                    b.HasIndex("CompanyAddressID");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            CompanyID = 1,
                            CompanyAddressID = 1,
                            CountryEstablishment = "Poland",
                            DateOfEstablishment = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is the first example company.",
                            Name = "Example Company 1",
                            Nip = "123-456-78-90",
                            Regon = "123456789"
                        },
                        new
                        {
                            CompanyID = 2,
                            CompanyAddressID = 2,
                            CountryEstablishment = "USA",
                            DateOfEstablishment = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is the second example company.",
                            Name = "Example Company 2",
                            Nip = "098-765-43-21",
                            Regon = "122143289"
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.Coupon", b =>
                {
                    b.Property<int>("CouponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("NumberOfUses")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CouponID");

                    b.HasIndex("UserId");

                    b.ToTable("Coupon");

                    b.HasData(
                        new
                        {
                            CouponID = 1,
                            Description = "10% discount on your first purchase",
                            DiscountPercentage = 10,
                            ExpireDate = new DateTime(2023, 5, 24, 23, 13, 36, 452, DateTimeKind.Local).AddTicks(3503),
                            Name = "WELCOME10",
                            NumberOfUses = 0,
                            UserId = 1
                        },
                        new
                        {
                            CouponID = 2,
                            Description = "15% discount on your next purchase",
                            DiscountPercentage = 15,
                            ExpireDate = new DateTime(2023, 6, 24, 23, 13, 36, 452, DateTimeKind.Local).AddTicks(3509),
                            Name = "SPRING15",
                            NumberOfUses = 0,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Other")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ItemID");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            Condition = "New",
                            Description = "Brand new smartphone with great features",
                            Manufacturer = "Samsung",
                            Model = "Galaxy S21",
                            Name = "Smartphone",
                            Other = "Comes with original packaging and accessories"
                        },
                        new
                        {
                            ItemID = 2,
                            Condition = "Used",
                            Description = "Powerful laptop with high-end specs",
                            Manufacturer = "Dell",
                            Model = "XPS 13",
                            Name = "Laptop",
                            Other = "Includes charger and carrying case"
                        },
                        new
                        {
                            ItemID = 3,
                            Condition = "Like new",
                            Description = "Wireless noise-cancelling headphones",
                            Manufacturer = "Sony",
                            Model = "WH-1000XM4",
                            Name = "Headphones",
                            Other = "Comes with charging cable and carrying case"
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AuctionPortal.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AuctionPortal.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<int>("AuctionID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("AuctionID");

                    b.HasIndex("UserID");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewID = 1,
                            AuctionID = 1,
                            Description = "I had a very positive experience with this seller. The item arrived quickly and was exactly as described.",
                            IsPositive = true,
                            Title = "Great seller",
                            UserID = 1
                        },
                        new
                        {
                            ReviewID = 2,
                            AuctionID = 2,
                            Description = "I purchased this product and it exceeded my expectations. The quality was great and it worked perfectly.",
                            IsPositive = true,
                            Title = "Excellent product",
                            UserID = 1
                        },
                        new
                        {
                            ReviewID = 3,
                            AuctionID = 3,
                            Description = "The item was shipped quickly and arrived in perfect condition. I would definitely buy from this seller again.",
                            IsPositive = true,
                            Title = "Fast shipping",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryID"));

                    b.Property<int?>("CategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("SubCategory");

                    b.HasData(
                        new
                        {
                            SubCategoryID = 1,
                            CategoryID = 1,
                            ImageURL = "https://grube.pl/wp-content/uploads/2017/07/product-135.jpg",
                            Name = "Laptops"
                        },
                        new
                        {
                            SubCategoryID = 2,
                            CategoryID = 1,
                            ImageURL = "https://grube.pl/wp-content/uploads/2017/07/product-135.jpg",
                            Name = "Smartphones"
                        },
                        new
                        {
                            SubCategoryID = 3,
                            CategoryID = 2,
                            ImageURL = "https://grube.pl/wp-content/uploads/2017/07/product-135.jpg",
                            Name = "Furniture"
                        },
                        new
                        {
                            SubCategoryID = 4,
                            CategoryID = 2,
                            ImageURL = "https://grube.pl/wp-content/uploads/2017/07/product-135.jpg",
                            Name = "Kitchen appliances"
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Nip")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            AddressID = 1,
                            ConcurrencyStamp = "f4138ce2-057f-4528-9fc6-67b5139212f6",
                            Email = "johndoe@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "John",
                            Nip = 0,
                            PhoneNumberConfirmed = false,
                            RegistationDate = new DateTime(2023, 4, 17, 23, 13, 36, 451, DateTimeKind.Local).AddTicks(9296),
                            Surname = "Doe",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            AddressID = 2,
                            CompanyID = 1,
                            ConcurrencyStamp = "2614112f-4005-4925-bfe3-0199b85a8ec7",
                            Email = "janedoe@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Jane",
                            Nip = 0,
                            PhoneNumberConfirmed = false,
                            RegistationDate = new DateTime(2023, 4, 21, 23, 13, 36, 451, DateTimeKind.Local).AddTicks(9341),
                            Surname = "Doe",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.Warranty", b =>
                {
                    b.Property<int>("WarrantyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarrantyID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durantion")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarrantyID");

                    b.ToTable("Warranty");

                    b.HasData(
                        new
                        {
                            WarrantyID = 1,
                            Description = "Basic warranty for 1 year.",
                            Durantion = 12,
                            Name = "Basic"
                        },
                        new
                        {
                            WarrantyID = 2,
                            Description = "Extended warranty for 2 years.",
                            Durantion = 24,
                            Name = "Extended"
                        },
                        new
                        {
                            WarrantyID = 3,
                            Description = "Premium warranty for 3 years.",
                            Durantion = 36,
                            Name = "Premium"
                        });
                });

            modelBuilder.Entity("MVCAuctionPortal.Models.Basket", b =>
                {
                    b.Property<int>("BasketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BasketID"));

                    b.Property<int>("NumberOfItems")
                        .HasColumnType("int");

                    b.Property<float>("SummaryPrice")
                        .HasColumnType("real");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BasketID");

                    b.HasIndex("UserID");

                    b.ToTable("Basket");

                    b.HasData(
                        new
                        {
                            BasketID = 1,
                            NumberOfItems = 2,
                            SummaryPrice = 50f,
                            UserID = 1
                        },
                        new
                        {
                            BasketID = 2,
                            NumberOfItems = 1,
                            SummaryPrice = 15f,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("MVCAuctionPortal.Models.BasketAndAuction", b =>
                {
                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Selected")
                        .HasColumnType("bit");

                    b.HasKey("AuctionId", "BasketId");

                    b.HasIndex("BasketId");

                    b.ToTable("BasketAndAuctions", (string)null);
                });

            modelBuilder.Entity("MVCAuctionPortal.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            ImageURL = "https://grube.pl/wp-content/uploads/2017/07/product-135.jpg",
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryID = 2,
                            ImageURL = "https://grube.pl/wp-content/uploads/2017/07/product-135.jpg",
                            Name = "Home and Garden"
                        },
                        new
                        {
                            CategoryID = 3,
                            ImageURL = "https://grube.pl/wp-content/uploads/2017/07/product-135.jpg",
                            Name = "Fashion"
                        },
                        new
                        {
                            CategoryID = 4,
                            ImageURL = "https://grube.pl/wp-content/uploads/2017/07/product-135.jpg",
                            Name = "Toys and Games"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "dd6b1aca-cce9-451b-b746-9bd95eda16fa",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "3cc48986-020f-405b-a4d4-fc747afd0778",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "1e056af0-bb65-4702-b384-10838120fc41",
                            Name = "Seller",
                            NormalizedName = "SELLER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("AuctionPortal.Models.Auction", b =>
                {
                    b.HasOne("MVCAuctionPortal.Models.Category", null)
                        .WithMany("Auctions")
                        .HasForeignKey("CategoryID");

                    b.HasOne("AuctionPortal.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionPortal.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionPortal.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionPortal.Models.Warranty", "Warranty")
                        .WithMany()
                        .HasForeignKey("WarrantyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("SubCategory");

                    b.Navigation("User");

                    b.Navigation("Warranty");
                });

            modelBuilder.Entity("AuctionPortal.Models.Company", b =>
                {
                    b.HasOne("AuctionPortal.Models.Address", "CompanyAddress")
                        .WithMany()
                        .HasForeignKey("CompanyAddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyAddress");
                });

            modelBuilder.Entity("AuctionPortal.Models.Coupon", b =>
                {
                    b.HasOne("AuctionPortal.Models.User", "User")
                        .WithMany("Coupons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionPortal.Models.OrderItem", b =>
                {
                    b.HasOne("AuctionPortal.Models.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionPortal.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AuctionPortal.Models.Review", b =>
                {
                    b.HasOne("AuctionPortal.Models.Auction", "Auction")
                        .WithMany("Reviews")
                        .HasForeignKey("AuctionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionPortal.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionPortal.Models.SubCategory", b =>
                {
                    b.HasOne("MVCAuctionPortal.Models.Category", "Categories")
                        .WithMany("SubCategory")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("AuctionPortal.Models.User", b =>
                {
                    b.HasOne("AuctionPortal.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionPortal.Models.Company", "Companies")
                        .WithMany()
                        .HasForeignKey("CompanyID");

                    b.Navigation("Address");

                    b.Navigation("Companies");
                });

            modelBuilder.Entity("MVCAuctionPortal.Models.Basket", b =>
                {
                    b.HasOne("AuctionPortal.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVCAuctionPortal.Models.BasketAndAuction", b =>
                {
                    b.HasOne("AuctionPortal.Models.Auction", "Auction")
                        .WithMany("BasketAndAuctions")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MVCAuctionPortal.Models.Basket", "Basket")
                        .WithMany("BasketAndAuctions")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Basket");
                });

            modelBuilder.Entity("AuctionPortal.Models.Auction", b =>
                {
                    b.Navigation("BasketAndAuctions");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AuctionPortal.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("AuctionPortal.Models.User", b =>
                {
                    b.Navigation("Coupons");
                });

            modelBuilder.Entity("MVCAuctionPortal.Models.Basket", b =>
                {
                    b.Navigation("BasketAndAuctions");
                });

            modelBuilder.Entity("MVCAuctionPortal.Models.Category", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("SubCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
