// <auto-generated />
using System;
using MVCAuctionPortal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCAuctionPortal.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20230502111934_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuctionPortal.Models.Auction", b =>
                {
                    b.Property<int>("AuctionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("Pieces")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("WarrantyID")
                        .HasColumnType("int");

                    b.HasKey("AuctionID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ItemID");

                    b.HasIndex("SubCategoryID");

                    b.HasIndex("UserID");

                    b.HasIndex("WarrantyID");

                    b.ToTable("Auction");

                    b.HasData(
                        new
                        {
                            AuctionID = 1,
                            DateOfIssue = new DateTime(2023, 5, 2, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(768),
                            EndDate = new DateTime(2023, 5, 9, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(780),
                            ImageURL = "https://cdn.x-kom.pl/i/setup/images/prod/big/product-new-big,,2022/5/pr_2022_5_17_12_20_15_932_03.jpg",
                            ItemID = 1,
                            Pieces = 5,
                            Price = 1000m,
                            SubCategoryID = 1,
                            Title = "Dell XPS 13",
                            UserID = 2,
                            WarrantyID = 1
                        },
                        new
                        {
                            AuctionID = 2,
                            DateOfIssue = new DateTime(2023, 5, 2, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(787),
                            EndDate = new DateTime(2023, 5, 9, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(789),
                            ImageURL = "https://www.proshop.pl/Images/915x900/3031704_4e1eacc41047.jpg",
                            ItemID = 2,
                            Pieces = 3,
                            Price = 700m,
                            SubCategoryID = 2,
                            Title = "Samsung Galaxy S22",
                            UserID = 2,
                            WarrantyID = 2
                        },
                        new
                        {
                            AuctionID = 3,
                            DateOfIssue = new DateTime(2023, 5, 2, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(791),
                            EndDate = new DateTime(2023, 5, 9, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(793),
                            ImageURL = "https://umebluje.pl/41747-large_default/sofa-modern-25-grafitowa.jpg",
                            ItemID = 3,
                            Pieces = 1,
                            Price = 1200m,
                            SubCategoryID = 3,
                            Title = "Modern Sofa",
                            UserID = 2,
                            WarrantyID = 3
                        },
                        new
                        {
                            AuctionID = 4,
                            DateOfIssue = new DateTime(2023, 5, 2, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(796),
                            EndDate = new DateTime(2023, 5, 9, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(797),
                            ImageURL = "https://m.media-amazon.com/images/I/61anBuiHUhL.jpg",
                            ItemID = 4,
                            Pieces = 2,
                            Price = 150m,
                            SubCategoryID = 4,
                            Title = "Kitchen Mixer",
                            UserID = 2,
                            WarrantyID = 3
                        },
                        new
                        {
                            AuctionID = 5,
                            DateOfIssue = new DateTime(2023, 5, 2, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(800),
                            EndDate = new DateTime(2023, 5, 9, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(801),
                            ImageURL = "https://n.nordstrommedia.com/id/sr3/ec6af5bc-c712-478b-b2d8-3723257766be.jpeg?h=365&w=240&dpr=2",
                            ItemID = 5,
                            Pieces = 4,
                            Price = 80m,
                            SubCategoryID = 5,
                            Title = "Elegant Dress",
                            UserID = 2,
                            WarrantyID = 3
                        },
                        new
                        {
                            AuctionID = 6,
                            DateOfIssue = new DateTime(2023, 5, 2, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(804),
                            EndDate = new DateTime(2023, 5, 9, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(805),
                            ImageURL = "https://m.media-amazon.com/images/I/61+hXDh7oIL._AC_UY1000_.jpg",
                            ItemID = 6,
                            Pieces = 3,
                            Price = 250m,
                            SubCategoryID = 6,
                            Title = "Stylish Watch",
                            UserID = 2,
                            WarrantyID = 2
                        },
                        new
                        {
                            AuctionID = 7,
                            DateOfIssue = new DateTime(2023, 5, 2, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(808),
                            EndDate = new DateTime(2023, 5, 9, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(809),
                            ImageURL = "https://www.lego.com/cdn/cs/set/assets/blt847a7b38581ded36/75315.png",
                            ItemID = 7,
                            Pieces = 10,
                            Price = 100m,
                            SubCategoryID = 7,
                            Title = "LEGO Star Wars Set",
                            UserID = 2,
                            WarrantyID = 1
                        },
                        new
                        {
                            AuctionID = 8,
                            DateOfIssue = new DateTime(2023, 5, 2, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(812),
                            EndDate = new DateTime(2023, 5, 9, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(813),
                            ImageURL = "https://ibkbike.vtexassets.com/arquivos/ids/593348-1200-auto?v=638060623332200000&width=1200&height=auto&aspect=true",
                            ItemID = 8,
                            Pieces = 2,
                            Price = 850m,
                            SubCategoryID = 8,
                            Title = "Road Bike",
                            UserID = 2,
                            WarrantyID = 2
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("CountryEstablishment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("DateOfEstablishment")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Regon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CompanyID");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            CompanyID = 1,
                            CountryEstablishment = "Poland",
                            DateOfEstablishment = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is the first example company.",
                            Name = "Example Company 1",
                            Nip = "123-456-78-90",
                            Regon = "123456789"
                        },
                        new
                        {
                            CompanyID = 2,
                            CountryEstablishment = "USA",
                            DateOfEstablishment = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is the second example company.",
                            Name = "Example Company 2",
                            Nip = "098-765-43-21",
                            Regon = "122143289"
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.Coupon", b =>
                {
                    b.Property<int>("CouponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("NumberOfUses")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CouponID");

                    b.HasIndex("UserId");

                    b.ToTable("Coupon");

                    b.HasData(
                        new
                        {
                            CouponID = 1,
                            Description = "10% discount on your first purchase",
                            DiscountPercentage = 10,
                            ExpireDate = new DateTime(2023, 6, 2, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(1036),
                            Name = "WELCOME10",
                            NumberOfUses = 5,
                            UserId = 1
                        },
                        new
                        {
                            CouponID = 2,
                            Description = "15% discount on your next purchase",
                            DiscountPercentage = 15,
                            ExpireDate = new DateTime(2023, 7, 2, 13, 19, 34, 438, DateTimeKind.Local).AddTicks(1043),
                            Name = "SPRING15",
                            NumberOfUses = 5,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Other")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ItemID");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            Condition = "Used",
                            Description = "Powerful Dell XPS 13 laptop with high-end specs",
                            Manufacturer = "Dell",
                            Model = "XPS 13",
                            Name = "Laptop",
                            Other = "Includes charger and carrying case"
                        },
                        new
                        {
                            ItemID = 2,
                            Condition = "New",
                            Description = "Brand new Samsung Galaxy S22 smartphone with great features",
                            Manufacturer = "Samsung",
                            Model = "Galaxy S22",
                            Name = "Smartphone",
                            Other = "Comes with original packaging and accessories"
                        },
                        new
                        {
                            ItemID = 3,
                            Condition = "Used",
                            Description = "Comfortable and stylish modern sofa",
                            Manufacturer = "IKEA",
                            Model = "KIVIK",
                            Name = "Sofa",
                            Other = "Some minor wear and tear"
                        },
                        new
                        {
                            ItemID = 4,
                            Condition = "New",
                            Description = "High-quality kitchen mixer for all your baking needs",
                            Manufacturer = "KitchenAid",
                            Model = "Stand Mixer",
                            Name = "Kitchen Mixer",
                            Other = "Comes with original packaging and accessories"
                        },
                        new
                        {
                            ItemID = 5,
                            Condition = "New",
                            Description = "Elegant and fashionable dress for special occasions",
                            Manufacturer = "Designer",
                            Model = "Evening Dress",
                            Name = "Elegant Dress",
                            Other = "Available in multiple sizes and colors"
                        },
                        new
                        {
                            ItemID = 6,
                            Condition = "New",
                            Description = "Elegant and fashionable Rolex Datejust 41 watch",
                            Manufacturer = "Rolex",
                            Model = "Datejust 41",
                            Name = "Stylish Watch",
                            Other = "Includes box and papers"
                        },
                        new
                        {
                            ItemID = 7,
                            Condition = "New",
                            Description = "Collectible LEGO Millennium Falcon set from the Star Wars series",
                            Manufacturer = "LEGO",
                            Model = "Millennium Falcon",
                            Name = "LEGO Star Wars Set",
                            Other = "Factory sealed"
                        },
                        new
                        {
                            ItemID = 8,
                            Condition = "Used",
                            Description = "Lightweight and fast Trek Domane SL 6 road bike",
                            Manufacturer = "Trek",
                            Model = "Domane SL 6",
                            Name = "Road Bike",
                            Other = "Recently serviced and in great condition"
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AuctionPortal.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AuctionPortal.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<int>("AuctionID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("AuctionID");

                    b.HasIndex("UserID");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewID = 1,
                            AuctionID = 1,
                            Description = "I had a very positive experience with this seller. The item arrived quickly and was exactly as described.",
                            IsPositive = true,
                            Title = "Great seller",
                            UserID = 1
                        },
                        new
                        {
                            ReviewID = 2,
                            AuctionID = 2,
                            Description = "I purchased this product and it exceeded my expectations. The quality was great and it worked perfectly.",
                            IsPositive = true,
                            Title = "Excellent product",
                            UserID = 1
                        },
                        new
                        {
                            ReviewID = 3,
                            AuctionID = 3,
                            Description = "The item was shipped quickly and arrived in perfect condition. I would definitely buy from this seller again.",
                            IsPositive = true,
                            Title = "Fast shipping",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryID"));

                    b.Property<int?>("CategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("SubCategory");

                    b.HasData(
                        new
                        {
                            SubCategoryID = 1,
                            CategoryID = 1,
                            ImageURL = "https://miro.medium.com/v2/resize:fit:928/1*SUK_D1dp3Acw1EjE1Cn6OA.png",
                            Name = "Laptops"
                        },
                        new
                        {
                            SubCategoryID = 2,
                            CategoryID = 1,
                            ImageURL = "https://cdn.pixabay.com/photo/2016/11/29/12/30/android-1869510_1280.jpg",
                            Name = "Smartphones"
                        },
                        new
                        {
                            SubCategoryID = 3,
                            CategoryID = 2,
                            ImageURL = "https://cdn.pixabay.com/photo/2016/11/18/17/20/living-room-1835923_1280.jpg",
                            Name = "Furniture"
                        },
                        new
                        {
                            SubCategoryID = 4,
                            CategoryID = 2,
                            ImageURL = "https://www.compliancegate.com/wp-content/uploads/2019/12/kitchen-appliances-safety-standards-eu.jpg",
                            Name = "Kitchen appliances"
                        },
                        new
                        {
                            SubCategoryID = 5,
                            CategoryID = 3,
                            ImageURL = "https://cdn.pixabay.com/photo/2017/08/01/08/29/people-2563491_1280.jpg",
                            Name = "Clothing"
                        },
                        new
                        {
                            SubCategoryID = 6,
                            CategoryID = 3,
                            ImageURL = "https://media.istockphoto.com/id/1181376840/photo/mock-up-blank-empty-digital-tablet-screen-on-beige-fashion-women-stylish-accessories-with-tag.jpg?s=612x612&w=0&k=20&c=AVOd71gDv5dRL9aic_9JmLyB0nvHkpSZ3uNkc9dl74o=",
                            Name = "Accessories"
                        },
                        new
                        {
                            SubCategoryID = 7,
                            CategoryID = 4,
                            ImageURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuBnq8qmkvccgSwZhLaxEIn5KzJqWSfdm5ow&usqp=CAU",
                            Name = "Board games"
                        },
                        new
                        {
                            SubCategoryID = 8,
                            CategoryID = 4,
                            ImageURL = "https://cdn.vox-cdn.com/thumbor/VK3R_SzCKTnG4egaSIMpxewl7M4=/0x0:2040x1360/1400x1400/filters:focal(1020x680:1021x681)/cdn.vox-cdn.com/uploads/chorus_asset/file/22236383/acastro_210113_1777_gamingstock_0002.jpg",
                            Name = "Video games"
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "70007488-670e-4628-8831-066a45e238f5",
                            Email = "johndoe@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "John",
                            PhoneNumberConfirmed = false,
                            RegistationDate = new DateTime(2023, 4, 25, 13, 19, 34, 437, DateTimeKind.Local).AddTicks(8619),
                            Surname = "Doe",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            CompanyID = 1,
                            ConcurrencyStamp = "1bb936c8-d2f0-4ac9-a232-77c1fd387e28",
                            Email = "janedoe@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Jane",
                            PhoneNumberConfirmed = false,
                            RegistationDate = new DateTime(2023, 4, 29, 13, 19, 34, 437, DateTimeKind.Local).AddTicks(8657),
                            Surname = "Doe",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("AuctionPortal.Models.Warranty", b =>
                {
                    b.Property<int>("WarrantyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarrantyID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durantion")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarrantyID");

                    b.ToTable("Warranty");

                    b.HasData(
                        new
                        {
                            WarrantyID = 1,
                            Description = "Basic warranty for 1 year.",
                            Durantion = 12,
                            Name = "Basic"
                        },
                        new
                        {
                            WarrantyID = 2,
                            Description = "Extended warranty for 2 years.",
                            Durantion = 24,
                            Name = "Extended"
                        },
                        new
                        {
                            WarrantyID = 3,
                            Description = "Premium warranty for 3 years.",
                            Durantion = 36,
                            Name = "Premium"
                        });
                });

            modelBuilder.Entity("MVCAuctionPortal.Models.Basket", b =>
                {
                    b.Property<int>("BasketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BasketID"));

                    b.Property<int>("NumberOfItems")
                        .HasColumnType("int");

                    b.Property<float>("SummaryPrice")
                        .HasColumnType("real");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BasketID");

                    b.HasIndex("UserID");

                    b.ToTable("Basket");

                    b.HasData(
                        new
                        {
                            BasketID = 1,
                            NumberOfItems = 3,
                            SummaryPrice = 50f,
                            UserID = 1
                        },
                        new
                        {
                            BasketID = 2,
                            NumberOfItems = 2,
                            SummaryPrice = 15f,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("MVCAuctionPortal.Models.BasketAndAuction", b =>
                {
                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Selected")
                        .HasColumnType("bit");

                    b.HasKey("AuctionId", "BasketId");

                    b.HasIndex("BasketId");

                    b.ToTable("BasketAndAuctions", (string)null);
                });

            modelBuilder.Entity("MVCAuctionPortal.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            ImageURL = "https://cdn.pixabay.com/photo/2016/03/27/19/43/smartphone-1283938_1280.jpg",
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryID = 2,
                            ImageURL = "https://cdn.pixabay.com/photo/2016/11/29/03/53/architecture-1867187_1280.jpg",
                            Name = "Home and Garden"
                        },
                        new
                        {
                            CategoryID = 3,
                            ImageURL = "https://cdn.pixabay.com/photo/2017/08/01/11/48/blue-2564660_1280.jpg",
                            Name = "Fashion"
                        },
                        new
                        {
                            CategoryID = 4,
                            ImageURL = "https://www.waysideinsurance.com/wp-content/uploads/2019/12/184/shopping-tips-to-avoid-dangerous-toys.jpg",
                            Name = "Toys and Games"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "90c686bf-5c12-43d8-80d3-4b1da2ff7756",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "036224a8-8acd-4250-937f-74569417d393",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "1b9e1a69-005b-4de1-9138-56059c84d138",
                            Name = "Seller",
                            NormalizedName = "SELLER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("AuctionPortal.Models.Auction", b =>
                {
                    b.HasOne("MVCAuctionPortal.Models.Category", null)
                        .WithMany("Auctions")
                        .HasForeignKey("CategoryID");

                    b.HasOne("AuctionPortal.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionPortal.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionPortal.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionPortal.Models.Warranty", "Warranty")
                        .WithMany()
                        .HasForeignKey("WarrantyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("SubCategory");

                    b.Navigation("User");

                    b.Navigation("Warranty");
                });

            modelBuilder.Entity("AuctionPortal.Models.Coupon", b =>
                {
                    b.HasOne("AuctionPortal.Models.User", "User")
                        .WithMany("Coupons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionPortal.Models.OrderItem", b =>
                {
                    b.HasOne("AuctionPortal.Models.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionPortal.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AuctionPortal.Models.Review", b =>
                {
                    b.HasOne("AuctionPortal.Models.Auction", "Auction")
                        .WithMany("Reviews")
                        .HasForeignKey("AuctionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionPortal.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionPortal.Models.SubCategory", b =>
                {
                    b.HasOne("MVCAuctionPortal.Models.Category", "Categories")
                        .WithMany("SubCategory")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("AuctionPortal.Models.User", b =>
                {
                    b.HasOne("AuctionPortal.Models.Company", "Companies")
                        .WithMany()
                        .HasForeignKey("CompanyID");

                    b.Navigation("Companies");
                });

            modelBuilder.Entity("MVCAuctionPortal.Models.Basket", b =>
                {
                    b.HasOne("AuctionPortal.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVCAuctionPortal.Models.BasketAndAuction", b =>
                {
                    b.HasOne("AuctionPortal.Models.Auction", "Auction")
                        .WithMany("BasketAndAuctions")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MVCAuctionPortal.Models.Basket", "Basket")
                        .WithMany("BasketAndAuctions")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Basket");
                });

            modelBuilder.Entity("AuctionPortal.Models.Auction", b =>
                {
                    b.Navigation("BasketAndAuctions");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AuctionPortal.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("AuctionPortal.Models.User", b =>
                {
                    b.Navigation("Coupons");
                });

            modelBuilder.Entity("MVCAuctionPortal.Models.Basket", b =>
                {
                    b.Navigation("BasketAndAuctions");
                });

            modelBuilder.Entity("MVCAuctionPortal.Models.Category", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("SubCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
